// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/model/image.proto (package model, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum model.Category
 */
export const Category = proto3.makeEnum(
  "model.Category",
  [
    {no: 0, name: "C_NONE"},
    {no: 1, name: "C_BASKETBALL_COMPETITION"},
    {no: 2, name: "C_BASKETBALL_COMPETITOR"},
    {no: 3, name: "C_FOOTBALL_COMPETITION"},
    {no: 4, name: "C_FOOTBALL_COMPETITOR"},
  ],
);

/**
 * @generated from enum model.BackgroundType
 */
export const BackgroundType = proto3.makeEnum(
  "model.BackgroundType",
  [
    {no: 0, name: "BT_NONE"},
    {no: 1, name: "BT_OUTSIDE"},
    {no: 2, name: "BT_FULL"},
  ],
);

/**
 * @generated from message model.Image
 */
export const Image = proto3.makeMessageType(
  "model.Image",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "category", kind: "enum", T: proto3.getEnumType(Category) },
    { no: 3, name: "background_type", kind: "enum", T: proto3.getEnumType(BackgroundType) },
    { no: 4, name: "labeler_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "url1", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "url2", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "url3", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "url_selected", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "url1_title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "url2_title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "url3_title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

