// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/model/image.proto (package model, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum model.Category
 */
export declare enum Category {
  /**
   * @generated from enum value: C_NONE = 0;
   */
  C_NONE = 0,

  /**
   * @generated from enum value: C_BASKETBALL_COMPETITION = 1;
   */
  C_BASKETBALL_COMPETITION = 1,

  /**
   * @generated from enum value: C_BASKETBALL_COMPETITOR = 2;
   */
  C_BASKETBALL_COMPETITOR = 2,

  /**
   * @generated from enum value: C_FOOTBALL_COMPETITION = 3;
   */
  C_FOOTBALL_COMPETITION = 3,

  /**
   * @generated from enum value: C_FOOTBALL_COMPETITOR = 4;
   */
  C_FOOTBALL_COMPETITOR = 4,
}

/**
 * @generated from enum model.BackgroundType
 */
export declare enum BackgroundType {
  /**
   * @generated from enum value: BT_NONE = 0;
   */
  BT_NONE = 0,

  /**
   * @generated from enum value: BT_OUTSIDE = 1;
   */
  BT_OUTSIDE = 1,

  /**
   * @generated from enum value: BT_FULL = 2;
   */
  BT_FULL = 2,
}

/**
 * @generated from message model.Image
 */
export declare class Image extends Message<Image> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: model.Category category = 2;
   */
  category: Category;

  /**
   * @generated from field: model.BackgroundType background_type = 3;
   */
  backgroundType: BackgroundType;

  /**
   * @generated from field: string labeler_id = 4;
   */
  labelerId: string;

  /**
   * @generated from field: string name = 5;
   */
  name: string;

  /**
   * @generated from field: string display_name = 6;
   */
  displayName: string;

  /**
   * @generated from field: string url1 = 7;
   */
  url1: string;

  /**
   * @generated from field: string url2 = 8;
   */
  url2: string;

  /**
   * @generated from field: string url3 = 9;
   */
  url3: string;

  /**
   * @generated from field: string url_selected = 10;
   */
  urlSelected: string;

  /**
   * @generated from field: string url1_title = 11;
   */
  url1Title: string;

  /**
   * @generated from field: string url2_title = 12;
   */
  url2Title: string;

  /**
   * @generated from field: string url3_title = 13;
   */
  url3Title: string;

  /**
   * @generated from field: string region = 14;
   */
  region: string;

  constructor(data?: PartialMessage<Image>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "model.Image";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Image;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Image;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Image;

  static equals(a: Image | PlainMessage<Image> | undefined, b: Image | PlainMessage<Image> | undefined): boolean;
}

