// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/model/user_info.proto (package model, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message model.UserInfo
 */
export declare class UserInfo extends Message<UserInfo> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: string email = 4;
   */
  email: string;

  constructor(data?: PartialMessage<UserInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "model.UserInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserInfo;

  static equals(a: UserInfo | PlainMessage<UserInfo> | undefined, b: UserInfo | PlainMessage<UserInfo> | undefined): boolean;
}

