version: "3.7"

services:
  labeler-backend:
    container_name: labeler-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - labeler-db
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: postgres
      DB_PASSWORD: password@1
      DB_HOST: labeler-db
      DB_PORT: 5432
      DB_NAME: backend_service
      DB_SSL_MODE: disable
      JWT_KEY: "some_key_ok"
      ENVIRONMENT: LOCAL
  labeler-db:
    container_name: labeler-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: password@1
      POSTGRES_DB: backend_service
    volumes:
      - "./tmp/db/backend_service:/var/lib/postgresql/data"
    ports:
      - 5432:5432
