// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/count_my_labeled_images.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message rpc.CountMyLabeledImagesRequest
 */
export const CountMyLabeledImagesRequest = proto3.makeMessageType(
  "rpc.CountMyLabeledImagesRequest",
  [],
);

/**
 * @generated from message rpc.CountMyLabeledImagesResponse
 */
export const CountMyLabeledImagesResponse = proto3.makeMessageType(
  "rpc.CountMyLabeledImagesResponse",
  () => [
    { no: 1, name: "count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

