// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/count_my_labeled_images.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message rpc.CountMyLabeledImagesRequest
 */
export declare class CountMyLabeledImagesRequest extends Message<CountMyLabeledImagesRequest> {
  constructor(data?: PartialMessage<CountMyLabeledImagesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.CountMyLabeledImagesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CountMyLabeledImagesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CountMyLabeledImagesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CountMyLabeledImagesRequest;

  static equals(a: CountMyLabeledImagesRequest | PlainMessage<CountMyLabeledImagesRequest> | undefined, b: CountMyLabeledImagesRequest | PlainMessage<CountMyLabeledImagesRequest> | undefined): boolean;
}

/**
 * @generated from message rpc.CountMyLabeledImagesResponse
 */
export declare class CountMyLabeledImagesResponse extends Message<CountMyLabeledImagesResponse> {
  /**
   * @generated from field: int64 count = 1;
   */
  count: bigint;

  constructor(data?: PartialMessage<CountMyLabeledImagesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.CountMyLabeledImagesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CountMyLabeledImagesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CountMyLabeledImagesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CountMyLabeledImagesResponse;

  static equals(a: CountMyLabeledImagesResponse | PlainMessage<CountMyLabeledImagesResponse> | undefined, b: CountMyLabeledImagesResponse | PlainMessage<CountMyLabeledImagesResponse> | undefined): boolean;
}

