// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/get_image_to_label.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Image } from "../model/image_pb.js";

/**
 * @generated from message rpc.GetImageToLabelRequest
 */
export const GetImageToLabelRequest = proto3.makeMessageType(
  "rpc.GetImageToLabelRequest",
  [],
);

/**
 * @generated from message rpc.GetImageToLabelResponse
 */
export const GetImageToLabelResponse = proto3.makeMessageType(
  "rpc.GetImageToLabelResponse",
  () => [
    { no: 1, name: "image", kind: "message", T: Image },
  ],
);

