// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/get_my_labeled_image.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Category, Image } from "../model/image_pb.js";

/**
 * @generated from message rpc.GetMyLabeledImageRequest
 */
export const GetMyLabeledImageRequest = proto3.makeMessageType(
  "rpc.GetMyLabeledImageRequest",
  () => [
    { no: 1, name: "category", kind: "enum", T: proto3.getEnumType(Category) },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message rpc.GetMyLabeledImageResponse
 */
export const GetMyLabeledImageResponse = proto3.makeMessageType(
  "rpc.GetMyLabeledImageResponse",
  () => [
    { no: 1, name: "image", kind: "message", T: Image },
  ],
);

