// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/get_image_to_label.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Image } from "../model/image_pb.js";

/**
 * @generated from message rpc.GetImageToLabelRequest
 */
export declare class GetImageToLabelRequest extends Message<GetImageToLabelRequest> {
  constructor(data?: PartialMessage<GetImageToLabelRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.GetImageToLabelRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetImageToLabelRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetImageToLabelRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetImageToLabelRequest;

  static equals(a: GetImageToLabelRequest | PlainMessage<GetImageToLabelRequest> | undefined, b: GetImageToLabelRequest | PlainMessage<GetImageToLabelRequest> | undefined): boolean;
}

/**
 * @generated from message rpc.GetImageToLabelResponse
 */
export declare class GetImageToLabelResponse extends Message<GetImageToLabelResponse> {
  /**
   * @generated from field: model.Image image = 1;
   */
  image?: Image;

  constructor(data?: PartialMessage<GetImageToLabelResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.GetImageToLabelResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetImageToLabelResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetImageToLabelResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetImageToLabelResponse;

  static equals(a: GetImageToLabelResponse | PlainMessage<GetImageToLabelResponse> | undefined, b: GetImageToLabelResponse | PlainMessage<GetImageToLabelResponse> | undefined): boolean;
}

