// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/get_labeled_images.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Category, Image } from "../model/image_pb.js";

/**
 * @generated from message rpc.GetLabeledImagesRequest
 */
export const GetLabeledImagesRequest = proto3.makeMessageType(
  "rpc.GetLabeledImagesRequest",
  () => [
    { no: 1, name: "labeler_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "page", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "category", kind: "enum", T: proto3.getEnumType(Category) },
  ],
);

/**
 * @generated from message rpc.GetLabeledImagesResponse
 */
export const GetLabeledImagesResponse = proto3.makeMessageType(
  "rpc.GetLabeledImagesResponse",
  () => [
    { no: 1, name: "images", kind: "message", T: Image, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

