// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/get_labeled_images.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Category, Image } from "../model/image_pb.js";

/**
 * @generated from message rpc.GetLabeledImagesRequest
 */
export declare class GetLabeledImagesRequest extends Message<GetLabeledImagesRequest> {
  /**
   * @generated from field: string labeler_id = 1;
   */
  labelerId: string;

  /**
   * @generated from field: int64 page = 2;
   */
  page: bigint;

  /**
   * @generated from field: int64 size = 3;
   */
  size: bigint;

  /**
   * @generated from field: model.Category category = 4;
   */
  category: Category;

  constructor(data?: PartialMessage<GetLabeledImagesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.GetLabeledImagesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLabeledImagesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLabeledImagesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLabeledImagesRequest;

  static equals(a: GetLabeledImagesRequest | PlainMessage<GetLabeledImagesRequest> | undefined, b: GetLabeledImagesRequest | PlainMessage<GetLabeledImagesRequest> | undefined): boolean;
}

/**
 * @generated from message rpc.GetLabeledImagesResponse
 */
export declare class GetLabeledImagesResponse extends Message<GetLabeledImagesResponse> {
  /**
   * @generated from field: repeated model.Image images = 1;
   */
  images: Image[];

  /**
   * @generated from field: int64 total = 2;
   */
  total: bigint;

  constructor(data?: PartialMessage<GetLabeledImagesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.GetLabeledImagesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLabeledImagesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLabeledImagesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLabeledImagesResponse;

  static equals(a: GetLabeledImagesResponse | PlainMessage<GetLabeledImagesResponse> | undefined, b: GetLabeledImagesResponse | PlainMessage<GetLabeledImagesResponse> | undefined): boolean;
}

