// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/rollback_labeled_image.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Category } from "../model/image_pb.js";

/**
 * @generated from message rpc.RollbackLabeledImageRequest
 */
export declare class RollbackLabeledImageRequest extends Message<RollbackLabeledImageRequest> {
  /**
   * @generated from field: model.Category category = 1;
   */
  category: Category;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  constructor(data?: PartialMessage<RollbackLabeledImageRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.RollbackLabeledImageRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RollbackLabeledImageRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RollbackLabeledImageRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RollbackLabeledImageRequest;

  static equals(a: RollbackLabeledImageRequest | PlainMessage<RollbackLabeledImageRequest> | undefined, b: RollbackLabeledImageRequest | PlainMessage<RollbackLabeledImageRequest> | undefined): boolean;
}

/**
 * @generated from message rpc.RollbackLabeledImageResponse
 */
export declare class RollbackLabeledImageResponse extends Message<RollbackLabeledImageResponse> {
  constructor(data?: PartialMessage<RollbackLabeledImageResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.RollbackLabeledImageResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RollbackLabeledImageResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RollbackLabeledImageResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RollbackLabeledImageResponse;

  static equals(a: RollbackLabeledImageResponse | PlainMessage<RollbackLabeledImageResponse> | undefined, b: RollbackLabeledImageResponse | PlainMessage<RollbackLabeledImageResponse> | undefined): boolean;
}

