// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/rollback_labeled_image.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Category } from "../model/image_pb.js";

/**
 * @generated from message rpc.RollbackLabeledImageRequest
 */
export const RollbackLabeledImageRequest = proto3.makeMessageType(
  "rpc.RollbackLabeledImageRequest",
  () => [
    { no: 1, name: "category", kind: "enum", T: proto3.getEnumType(Category) },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message rpc.RollbackLabeledImageResponse
 */
export const RollbackLabeledImageResponse = proto3.makeMessageType(
  "rpc.RollbackLabeledImageResponse",
  [],
);

