// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/sign_up.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { UserInfo } from "../model/user_info_pb.js";

/**
 * @generated from message rpc.SignUpRequest
 */
export const SignUpRequest = proto3.makeMessageType(
  "rpc.SignUpRequest",
  () => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message rpc.SignUpResponse
 */
export const SignUpResponse = proto3.makeMessageType(
  "rpc.SignUpResponse",
  () => [
    { no: 1, name: "info", kind: "message", T: UserInfo },
  ],
);

