// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/sign_up.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { UserInfo } from "../model/user_info_pb.js";

/**
 * @generated from message rpc.SignUpRequest
 */
export declare class SignUpRequest extends Message<SignUpRequest> {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * @generated from field: string email = 4;
   */
  email: string;

  constructor(data?: PartialMessage<SignUpRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.SignUpRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignUpRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignUpRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignUpRequest;

  static equals(a: SignUpRequest | PlainMessage<SignUpRequest> | undefined, b: SignUpRequest | PlainMessage<SignUpRequest> | undefined): boolean;
}

/**
 * @generated from message rpc.SignUpResponse
 */
export declare class SignUpResponse extends Message<SignUpResponse> {
  /**
   * @generated from field: model.UserInfo info = 1;
   */
  info?: UserInfo;

  constructor(data?: PartialMessage<SignUpResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.SignUpResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignUpResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignUpResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignUpResponse;

  static equals(a: SignUpResponse | PlainMessage<SignUpResponse> | undefined, b: SignUpResponse | PlainMessage<SignUpResponse> | undefined): boolean;
}

