// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/update_image_after_labeled.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { BackgroundType, Category } from "../model/image_pb.js";

/**
 * @generated from message rpc.UpdateImageAfterLabeledRequest
 */
export declare class UpdateImageAfterLabeledRequest extends Message<UpdateImageAfterLabeledRequest> {
  /**
   * @generated from field: model.Category category = 1;
   */
  category: Category;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string url_selected = 3;
   */
  urlSelected: string;

  /**
   * @generated from field: model.BackgroundType background_type = 4;
   */
  backgroundType: BackgroundType;

  constructor(data?: PartialMessage<UpdateImageAfterLabeledRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.UpdateImageAfterLabeledRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateImageAfterLabeledRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateImageAfterLabeledRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateImageAfterLabeledRequest;

  static equals(a: UpdateImageAfterLabeledRequest | PlainMessage<UpdateImageAfterLabeledRequest> | undefined, b: UpdateImageAfterLabeledRequest | PlainMessage<UpdateImageAfterLabeledRequest> | undefined): boolean;
}

/**
 * @generated from message rpc.UpdateImageAfterLabeledResponse
 */
export declare class UpdateImageAfterLabeledResponse extends Message<UpdateImageAfterLabeledResponse> {
  constructor(data?: PartialMessage<UpdateImageAfterLabeledResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "rpc.UpdateImageAfterLabeledResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateImageAfterLabeledResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateImageAfterLabeledResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateImageAfterLabeledResponse;

  static equals(a: UpdateImageAfterLabeledResponse | PlainMessage<UpdateImageAfterLabeledResponse> | undefined, b: UpdateImageAfterLabeledResponse | PlainMessage<UpdateImageAfterLabeledResponse> | undefined): boolean;
}

