// @generated by protoc-gen-es v1.2.1 with parameter "target=js+dts"
// @generated from file auth/rpc/update_image_after_labeled.proto (package rpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { BackgroundType, Category } from "../model/image_pb.js";

/**
 * @generated from message rpc.UpdateImageAfterLabeledRequest
 */
export const UpdateImageAfterLabeledRequest = proto3.makeMessageType(
  "rpc.UpdateImageAfterLabeledRequest",
  () => [
    { no: 1, name: "category", kind: "enum", T: proto3.getEnumType(Category) },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "url_selected", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "background_type", kind: "enum", T: proto3.getEnumType(BackgroundType) },
  ],
);

/**
 * @generated from message rpc.UpdateImageAfterLabeledResponse
 */
export const UpdateImageAfterLabeledResponse = proto3.makeMessageType(
  "rpc.UpdateImageAfterLabeledResponse",
  [],
);

