// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/rpc/count_my_labeled_images.proto

package rpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CountMyLabeledImagesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CountMyLabeledImagesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CountMyLabeledImagesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CountMyLabeledImagesRequestMultiError, or nil if none found.
func (m *CountMyLabeledImagesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CountMyLabeledImagesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CountMyLabeledImagesRequestMultiError(errors)
	}

	return nil
}

// CountMyLabeledImagesRequestMultiError is an error wrapping multiple
// validation errors returned by CountMyLabeledImagesRequest.ValidateAll() if
// the designated constraints aren't met.
type CountMyLabeledImagesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CountMyLabeledImagesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CountMyLabeledImagesRequestMultiError) AllErrors() []error { return m }

// CountMyLabeledImagesRequestValidationError is the validation error returned
// by CountMyLabeledImagesRequest.Validate if the designated constraints
// aren't met.
type CountMyLabeledImagesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CountMyLabeledImagesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CountMyLabeledImagesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CountMyLabeledImagesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CountMyLabeledImagesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CountMyLabeledImagesRequestValidationError) ErrorName() string {
	return "CountMyLabeledImagesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CountMyLabeledImagesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCountMyLabeledImagesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CountMyLabeledImagesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CountMyLabeledImagesRequestValidationError{}

// Validate checks the field values on CountMyLabeledImagesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CountMyLabeledImagesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CountMyLabeledImagesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CountMyLabeledImagesResponseMultiError, or nil if none found.
func (m *CountMyLabeledImagesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CountMyLabeledImagesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Count

	if len(errors) > 0 {
		return CountMyLabeledImagesResponseMultiError(errors)
	}

	return nil
}

// CountMyLabeledImagesResponseMultiError is an error wrapping multiple
// validation errors returned by CountMyLabeledImagesResponse.ValidateAll() if
// the designated constraints aren't met.
type CountMyLabeledImagesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CountMyLabeledImagesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CountMyLabeledImagesResponseMultiError) AllErrors() []error { return m }

// CountMyLabeledImagesResponseValidationError is the validation error returned
// by CountMyLabeledImagesResponse.Validate if the designated constraints
// aren't met.
type CountMyLabeledImagesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CountMyLabeledImagesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CountMyLabeledImagesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CountMyLabeledImagesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CountMyLabeledImagesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CountMyLabeledImagesResponseValidationError) ErrorName() string {
	return "CountMyLabeledImagesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CountMyLabeledImagesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCountMyLabeledImagesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CountMyLabeledImagesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CountMyLabeledImagesResponseValidationError{}
