// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: auth/rpc/get_labeled_images.proto

package rpc

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	model "github.com/manhrev/labeler/pkg/api/go/auth/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLabeledImagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabelerId string         `protobuf:"bytes,1,opt,name=labeler_id,json=labelerId,proto3" json:"labeler_id,omitempty"`
	Page      int64          `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size      int64          `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Category  model.Category `protobuf:"varint,4,opt,name=category,proto3,enum=model.Category" json:"category,omitempty"`
}

func (x *GetLabeledImagesRequest) Reset() {
	*x = GetLabeledImagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_rpc_get_labeled_images_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLabeledImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabeledImagesRequest) ProtoMessage() {}

func (x *GetLabeledImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rpc_get_labeled_images_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabeledImagesRequest.ProtoReflect.Descriptor instead.
func (*GetLabeledImagesRequest) Descriptor() ([]byte, []int) {
	return file_auth_rpc_get_labeled_images_proto_rawDescGZIP(), []int{0}
}

func (x *GetLabeledImagesRequest) GetLabelerId() string {
	if x != nil {
		return x.LabelerId
	}
	return ""
}

func (x *GetLabeledImagesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLabeledImagesRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetLabeledImagesRequest) GetCategory() model.Category {
	if x != nil {
		return x.Category
	}
	return model.Category(0)
}

type GetLabeledImagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Images []*model.Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *GetLabeledImagesResponse) Reset() {
	*x = GetLabeledImagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_rpc_get_labeled_images_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLabeledImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLabeledImagesResponse) ProtoMessage() {}

func (x *GetLabeledImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rpc_get_labeled_images_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLabeledImagesResponse.ProtoReflect.Descriptor instead.
func (*GetLabeledImagesResponse) Descriptor() ([]byte, []int) {
	return file_auth_rpc_get_labeled_images_proto_rawDescGZIP(), []int{1}
}

func (x *GetLabeledImagesResponse) GetImages() []*model.Image {
	if x != nil {
		return x.Images
	}
	return nil
}

var File_auth_rpc_get_labeled_images_proto protoreflect.FileDescriptor

var file_auth_rpc_get_labeled_images_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x16, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x82, 0x01, 0x02,
	0x10, 0x01, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x40, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e,
	0x68, 0x72, 0x65, 0x76, 0x2f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x72, 0x70, 0x63,
	0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_rpc_get_labeled_images_proto_rawDescOnce sync.Once
	file_auth_rpc_get_labeled_images_proto_rawDescData = file_auth_rpc_get_labeled_images_proto_rawDesc
)

func file_auth_rpc_get_labeled_images_proto_rawDescGZIP() []byte {
	file_auth_rpc_get_labeled_images_proto_rawDescOnce.Do(func() {
		file_auth_rpc_get_labeled_images_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_rpc_get_labeled_images_proto_rawDescData)
	})
	return file_auth_rpc_get_labeled_images_proto_rawDescData
}

var file_auth_rpc_get_labeled_images_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_rpc_get_labeled_images_proto_goTypes = []interface{}{
	(*GetLabeledImagesRequest)(nil),  // 0: rpc.GetLabeledImagesRequest
	(*GetLabeledImagesResponse)(nil), // 1: rpc.GetLabeledImagesResponse
	(model.Category)(0),              // 2: model.Category
	(*model.Image)(nil),              // 3: model.Image
}
var file_auth_rpc_get_labeled_images_proto_depIdxs = []int32{
	2, // 0: rpc.GetLabeledImagesRequest.category:type_name -> model.Category
	3, // 1: rpc.GetLabeledImagesResponse.images:type_name -> model.Image
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_rpc_get_labeled_images_proto_init() }
func file_auth_rpc_get_labeled_images_proto_init() {
	if File_auth_rpc_get_labeled_images_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_rpc_get_labeled_images_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLabeledImagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_rpc_get_labeled_images_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLabeledImagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_rpc_get_labeled_images_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_rpc_get_labeled_images_proto_goTypes,
		DependencyIndexes: file_auth_rpc_get_labeled_images_proto_depIdxs,
		MessageInfos:      file_auth_rpc_get_labeled_images_proto_msgTypes,
	}.Build()
	File_auth_rpc_get_labeled_images_proto = out.File
	file_auth_rpc_get_labeled_images_proto_rawDesc = nil
	file_auth_rpc_get_labeled_images_proto_goTypes = nil
	file_auth_rpc_get_labeled_images_proto_depIdxs = nil
}
