// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/rpc/get_image_to_label.proto

package rpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetImageToLabelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetImageToLabelRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetImageToLabelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetImageToLabelRequestMultiError, or nil if none found.
func (m *GetImageToLabelRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetImageToLabelRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetImageToLabelRequestMultiError(errors)
	}

	return nil
}

// GetImageToLabelRequestMultiError is an error wrapping multiple validation
// errors returned by GetImageToLabelRequest.ValidateAll() if the designated
// constraints aren't met.
type GetImageToLabelRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetImageToLabelRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetImageToLabelRequestMultiError) AllErrors() []error { return m }

// GetImageToLabelRequestValidationError is the validation error returned by
// GetImageToLabelRequest.Validate if the designated constraints aren't met.
type GetImageToLabelRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetImageToLabelRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetImageToLabelRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetImageToLabelRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetImageToLabelRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetImageToLabelRequestValidationError) ErrorName() string {
	return "GetImageToLabelRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetImageToLabelRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetImageToLabelRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetImageToLabelRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetImageToLabelRequestValidationError{}

// Validate checks the field values on GetImageToLabelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetImageToLabelResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetImageToLabelResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetImageToLabelResponseMultiError, or nil if none found.
func (m *GetImageToLabelResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetImageToLabelResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetImage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetImageToLabelResponseValidationError{
					field:  "Image",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetImageToLabelResponseValidationError{
					field:  "Image",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetImage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetImageToLabelResponseValidationError{
				field:  "Image",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetImageToLabelResponseMultiError(errors)
	}

	return nil
}

// GetImageToLabelResponseMultiError is an error wrapping multiple validation
// errors returned by GetImageToLabelResponse.ValidateAll() if the designated
// constraints aren't met.
type GetImageToLabelResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetImageToLabelResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetImageToLabelResponseMultiError) AllErrors() []error { return m }

// GetImageToLabelResponseValidationError is the validation error returned by
// GetImageToLabelResponse.Validate if the designated constraints aren't met.
type GetImageToLabelResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetImageToLabelResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetImageToLabelResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetImageToLabelResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetImageToLabelResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetImageToLabelResponseValidationError) ErrorName() string {
	return "GetImageToLabelResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetImageToLabelResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetImageToLabelResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetImageToLabelResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetImageToLabelResponseValidationError{}
