// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/rpc/update_image_after_labeled.proto

package rpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	model "github.com/manhrev/labeler/pkg/api/go/auth/model"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = model.BackgroundType(0)
)

// Validate checks the field values on UpdateImageAfterLabeledRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateImageAfterLabeledRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateImageAfterLabeledRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateImageAfterLabeledRequestMultiError, or nil if none found.
func (m *UpdateImageAfterLabeledRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateImageAfterLabeledRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _UpdateImageAfterLabeledRequest_Category_NotInLookup[m.GetCategory()]; ok {
		err := UpdateImageAfterLabeledRequestValidationError{
			field:  "Category",
			reason: "value must not be in list [0]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := model.Category_name[int32(m.GetCategory())]; !ok {
		err := UpdateImageAfterLabeledRequestValidationError{
			field:  "Category",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := UpdateImageAfterLabeledRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUrlSelected()) < 1 {
		err := UpdateImageAfterLabeledRequestValidationError{
			field:  "UrlSelected",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for BackgroundType

	if len(errors) > 0 {
		return UpdateImageAfterLabeledRequestMultiError(errors)
	}

	return nil
}

// UpdateImageAfterLabeledRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateImageAfterLabeledRequest.ValidateAll()
// if the designated constraints aren't met.
type UpdateImageAfterLabeledRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateImageAfterLabeledRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateImageAfterLabeledRequestMultiError) AllErrors() []error { return m }

// UpdateImageAfterLabeledRequestValidationError is the validation error
// returned by UpdateImageAfterLabeledRequest.Validate if the designated
// constraints aren't met.
type UpdateImageAfterLabeledRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateImageAfterLabeledRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateImageAfterLabeledRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateImageAfterLabeledRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateImageAfterLabeledRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateImageAfterLabeledRequestValidationError) ErrorName() string {
	return "UpdateImageAfterLabeledRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateImageAfterLabeledRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateImageAfterLabeledRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateImageAfterLabeledRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateImageAfterLabeledRequestValidationError{}

var _UpdateImageAfterLabeledRequest_Category_NotInLookup = map[model.Category]struct{}{
	0: {},
}

// Validate checks the field values on UpdateImageAfterLabeledResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateImageAfterLabeledResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateImageAfterLabeledResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateImageAfterLabeledResponseMultiError, or nil if none found.
func (m *UpdateImageAfterLabeledResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateImageAfterLabeledResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateImageAfterLabeledResponseMultiError(errors)
	}

	return nil
}

// UpdateImageAfterLabeledResponseMultiError is an error wrapping multiple
// validation errors returned by UpdateImageAfterLabeledResponse.ValidateAll()
// if the designated constraints aren't met.
type UpdateImageAfterLabeledResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateImageAfterLabeledResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateImageAfterLabeledResponseMultiError) AllErrors() []error { return m }

// UpdateImageAfterLabeledResponseValidationError is the validation error
// returned by UpdateImageAfterLabeledResponse.Validate if the designated
// constraints aren't met.
type UpdateImageAfterLabeledResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateImageAfterLabeledResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateImageAfterLabeledResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateImageAfterLabeledResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateImageAfterLabeledResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateImageAfterLabeledResponseValidationError) ErrorName() string {
	return "UpdateImageAfterLabeledResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateImageAfterLabeledResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateImageAfterLabeledResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateImageAfterLabeledResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateImageAfterLabeledResponseValidationError{}
