// @generated by protoc-gen-connect-es v0.9.1 with parameter "target=js+dts"
// @generated from file auth/auth.proto (package auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SignUpRequest, SignUpResponse } from "./rpc/sign_up_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { LoginRequest, LoginResponse } from "./rpc/login_pb.js";
import { MeRequest, MeResponse } from "./rpc/me_pb.js";
import { GetImageToLabelRequest, GetImageToLabelResponse } from "./rpc/get_image_to_label_pb.js";
import { UpdateImageAfterLabeledRequest, UpdateImageAfterLabeledResponse } from "./rpc/update_image_after_labeled_pb.js";
import { RollbackLabeledImageRequest, RollbackLabeledImageResponse } from "./rpc/rollback_labeled_image_pb.js";
import { GetMyLabeledImageRequest, GetMyLabeledImageResponse } from "./rpc/get_my_labeled_image_pb.js";

/**
 * @generated from service auth.AuthService
 */
export declare const AuthService: {
  readonly typeName: "auth.AuthService",
  readonly methods: {
    /**
     * @generated from rpc auth.AuthService.SignUp
     */
    readonly signUp: {
      readonly name: "SignUp",
      readonly I: typeof SignUpRequest,
      readonly O: typeof SignUpResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.Login
     */
    readonly login: {
      readonly name: "Login",
      readonly I: typeof LoginRequest,
      readonly O: typeof LoginResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.Me
     */
    readonly me: {
      readonly name: "Me",
      readonly I: typeof MeRequest,
      readonly O: typeof MeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.GetImageToLabel
     */
    readonly getImageToLabel: {
      readonly name: "GetImageToLabel",
      readonly I: typeof GetImageToLabelRequest,
      readonly O: typeof GetImageToLabelResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.UpdateImageAfterLabeled
     */
    readonly updateImageAfterLabeled: {
      readonly name: "UpdateImageAfterLabeled",
      readonly I: typeof UpdateImageAfterLabeledRequest,
      readonly O: typeof UpdateImageAfterLabeledResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.RollbackLabeledImage
     */
    readonly rollbackLabeledImage: {
      readonly name: "RollbackLabeledImage",
      readonly I: typeof RollbackLabeledImageRequest,
      readonly O: typeof RollbackLabeledImageResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.GetMyLabeledImage
     */
    readonly getMyLabeledImage: {
      readonly name: "GetMyLabeledImage",
      readonly I: typeof GetMyLabeledImageRequest,
      readonly O: typeof GetMyLabeledImageResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

